spring:
    profiles:
	active:
	- dev
---
spring:
    profiles:dev #开发环境
    application:
	name:mycloud-config-wcc-dev

---
spring:
    profiles:test #开发环境
    application:
	name:mycloud-config-wcc-test